apiVersion: apps/v1
kind: Deployment

metadata:
  name: user-service

spec:
  replicas: {{ .Values.user.replicas }}

  selector:
    matchLabels:
      app: user-service

  template:
    metadata:
      labels:
        app: user-service

    spec:
      containers:

        - name: user

          image: "{{ .Values.user.image.repository }}:{{ .Values.user.image.tag }}"

          ports:
            - containerPort: 80
